spring:
  # database url:
  datasource:
    url: jdbc:h2:mem:conferencedb
  h2:
    console:
      enabled: true

# port:
server:
  port: 8082

# resolve IP address from hostname:
eureka:
  instance:
    prefer-ip-address: true