spring:
  # database:
  datasource:
    url: jdbc:h2:mem:keynotedb
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test-rlm
          jwk-set-uri: http://localhost:8080/realms/test-rlm/protocol/openid-connect/certs
          authorities-claim-name: realm_access
#          authority-prefix: ROLE_

# port:
server:
  port: 8081

# resolve IP address from hostname:
eureka:
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    config-url: http://localhost:8081/v3/api-docs/swagger-config